name: HOFC
on:
  watch:
    types: started
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: |
        curl https://rclone.org/install.sh | sudo bash
        wget -q https://github.com/paninisa/papani/releases/download/v2/gclone.gz
        gunzip gclone.gz
        sudo mv gclone /usr/bin/gclone
        chmod +x /usr/bin/gclone
        sudo apt install unrar -y -q
    - name: Inject Rclone config
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      run: |
        wget -q https://github.com/$GITHUB_REPOSITORY/raw/main/accounts.rar
        unrar -p'${{ secrets.RAR_PSWD }}' e accounts.rar ~/accounts/
        index=`ls -l ~/accounts |grep "^-"|wc -l`
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${RCLONE_CONF/1.json/$((RANDOM%$index+1)).json}
        EOF
    - name: HDCTV
      run: |
        rclone lsd pt_part1:/HDChina_sTepHEn/ | sort -k 2 | awk '$2 >= "2021-07-24" && $2 <= "2021-07-27"' | awk '{print "- "$5"/*FEED.1080i*/**\n""+ "$5"/*-HDCTV/**"}' > hdc.output && echo "- **" >> hdc.output
        gclone copy ${{ secrets.FILE1_PATH }}  --stats-log-level NOTICE -P --stats 30s --cache-chunk-total-size 25G --transfers=12 --drive-chunk-size 128M  --max-backlog 1000 --drive-skip-depth 1 --checksum --filter-from hdc.output
    - name: OurTV
      run: |
        rclone lsd pt_part1:/OurBits_Panini/ | sort -k 2 | awk '$2 >= "2021-07-24" && $2 <= "2021-07-27"' | awk '{print "+ "$5"/*-OurTV/**"}' > ourtv.output && echo "- **" >> ourtv.output
        gclone copy ${{ secrets.FILE2_PATH }}  --stats-log-level NOTICE -P --stats 30s --cache-chunk-total-size 25G --transfers=12 --drive-chunk-size 128M --max-backlog 1000 --drive-skip-depth 1 --checksum  --filter-from ourtv.output
    - name: FLTTH
      run: |
        rclone lsd pt_part1:/OurBits_Panini/ | sort -k 2 | awk '$2 >= "2021-07-24" && $2 <= "2021-07-27"' | awk '{print "+ "$5"/*-FLTTH/**"}' > fltth.output && echo "- **" >> fltth.output
        gclone copy ${{ secrets.FILE3_PATH }}  --stats-log-level NOTICE -P --stats 30s --cache-chunk-total-size 25G --transfers=12 --drive-chunk-size 128M --max-backlog 1000 --drive-skip-depth 1 --checksum --filter-from fltth.output
    - name: CHDHKTV
      run: |
        rclone lsd pt_part1:/CHDBits_Panini/ | sort -k 2 | awk '$2 >= "2021-07-24" && $2 <= "2021-07-27"' | awk '{print "+ "$5"/*-CHDHKTV/**"}' > chdhktv.output && echo "- **" >> chdhktv.output
        gclone copy ${{ secrets.FILE4_PATH }}  --stats-log-level NOTICE -P --stats 30s --cache-chunk-total-size 25G --transfers=12 --drive-chunk-size 128M --max-backlog 1000 --drive-skip-depth 1 --checksum --filter-from chdhktv.output
